# AUTO-GENERATED by tools/mapgen.py - do not edit by hand
extends RefCounted
class_name MapData

const LAYOUT: PackedStringArray = [
	"#######################################",
	"#xccccccx#ooooooof#L#sSSsSSa#.#kkCCKCC#",
	"#ccc1cccc#otototoo#L#sssssss#.#kkkkkkk#",
	"#cccccccc#aoooooooD.#sSSsSSs#z#kkkkkkk#",
	"#cccccccc#oooNoooo#.Dsssssss#.HkkkkkkC#",
	"#cccccccc#otooooto#a#ssssssN#.#kkkkkkC#",
	"#bccccccN#foooooo+#.#bssssss#.#kk+kkkk#",
	"####H#########D####.####D####.#########",
	"#LLL........z................LLL..z..a#",
	"####D####.####D####.#########.####D####",
	"#xxwwwxw#.#B+eeeef#L#hhzhhhz#.#zooooof#",
	"#xwwwwwa#.#eeeeeee#L#hthhhth#.#otoooto#",
	"#awbwwzwD.#BezeNeeD.DhhhNhhhD.Doooooob#",
	"#wxwwwww#+#eeeeeee#.#hthhhth#.#ooooNoo#",
	"#Nwwwwxx#.#BeBee+e#.#ahhhhhh#.#otoooto#",
	"####D####.#########.####D####.#oooooof#",
	"#a....z...................LLL.###H#####",
	"####D####.####D####.####H#####vvvvvvvv#",
	"#BBdddBB#L#Tgggggx#.#xqqqqqqN#vxvvvvvx#",
	"#ddddddd#L#ggggggg#.#qqqqqzqq#vvvvvvvv#",
	"#NddddddD.#TgggNgg#bDqqqqqqqqHvvvvvvvv#",
	"#ddPdddd#.#gbgggggD.#qqq4qqqq#vvvvvvvv#",
	"#dddddda#L#Tggzggg#z#qqqqqqqq#vvvvvv6v#",
	"#BddddBd#a#ggaggxg#.#qaqqqqqx#vNvvvvva#",
	"#######################################",
]
